# Generated by Django 3.0.3 on 2020-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='latestbid',
            field=models.IntegerField(null=True),
        ),
    ]
