# Generated by Django 3.0.3 on 2020-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='startingBid',
            field=models.FloatField(),
        ),
    ]
